# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "TooNormal"
license = "MIT"
licenselink = "https://github.com/mikekasprzak/hugo-toonormal/blob/master/LICENSE"
description = "A fork of 'Paper' for my Blog"
homepage = "https://github.com/mikekasprzak/hugo-toonormal/"
tags = ["Responsive", "Simple", "Clean", "Light", "White", "Blog"]
features = ["Responsive", "One Column", "Blog"]
min_version = "0.57.1"

[author]
  name = "mikekasprzak"
  homepage = "https://toonormal.com/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
